
development:
  adapter: mysql2
  database: sghw_dev
  username: root
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: sghw_test
  username: root
  host: localhost
  pool: 5
  timeout: 5000
